spring:
  application:
    name: netflix_dgs

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netflix_dgs
    username: root
    password: rlgus585
    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      idle-timeout: 30000
      minimum-idle: 2
      connection-timeout: 10000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments:
    open-in-view: true #OSIV ( Open Session I View 설정 ) Controller에서 Entity를 조회할 때, 트랜잭션이 View 렌더링까지 유지가 되는지 설정
  sql:
    init:
      mode: ALWAYS


